/* tslint:disable */
/* eslint-disable */
/**
 * MovieSpot API
 * Especificações da API para o back-end da aplicação MovieSpot
 *
 * The version of the OpenAPI document: 1/
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ApiV1LoginPost200Response
 */
export interface ApiV1LoginPost200Response {
    /**
     * 
     * @type {string}
     * @memberof ApiV1LoginPost200Response
     */
    'token': string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1LoginPost200Response
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1LoginPost200Response
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1LoginPost200Response
     */
    'role': ApiV1LoginPost200ResponseRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiV1LoginPost200Response
     */
    'cpf': string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1LoginPost200Response
     */
    'email': string;
}

export const ApiV1LoginPost200ResponseRoleEnum = {
    Client: 'CLIENT',
    Admin: 'ADMIN',
    Owner: 'OWNER'
} as const;

export type ApiV1LoginPost200ResponseRoleEnum = typeof ApiV1LoginPost200ResponseRoleEnum[keyof typeof ApiV1LoginPost200ResponseRoleEnum];


