/* tslint:disable */
/* eslint-disable */
/**
 * MovieSpot API
 * Especificações da API para o back-end da aplicação MovieSpot
 *
 * The version of the OpenAPI document: 1/
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ApiV1RentedMoviesPostRequest
 */
export interface ApiV1RentedMoviesPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiV1RentedMoviesPostRequest
     */
    'userId': string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1RentedMoviesPostRequest
     */
    'movieId': string;
    /**
     * 
     * @type {object}
     * @memberof ApiV1RentedMoviesPostRequest
     */
    'dueDate'?: object;
}

