/* tslint:disable */
/* eslint-disable */
/**
 * MovieSpot API
 * Especificações da API para o back-end da aplicação MovieSpot
 *
 * The version of the OpenAPI document: 1/
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ApiV1MoviesIdPutRequest
 */
export interface ApiV1MoviesIdPutRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiV1MoviesIdPutRequest
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1MoviesIdPutRequest
     */
    'subTitle'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1MoviesIdPutRequest
     */
    'description'?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiV1MoviesIdPutRequest
     */
    'duration'?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiV1MoviesIdPutRequest
     */
    'releaseDate'?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiV1MoviesIdPutRequest
     */
    'minimumAge'?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV1MoviesIdPutRequest
     */
    'rentPrice'?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof ApiV1MoviesIdPutRequest
     */
    'category'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ApiV1MoviesIdPutRequest
     */
    'trailerUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1MoviesIdPutRequest
     */
    'movieUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1MoviesIdPutRequest
     */
    'imageUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1MoviesIdPutRequest
     */
    'director'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ApiV1MoviesIdPutRequest
     */
    'actors'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ApiV1MoviesIdPutRequest
     */
    'producers'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ApiV1MoviesIdPutRequest
     */
    'studio'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1MoviesIdPutRequest
     */
    'contentClassification'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ApiV1MoviesIdPutRequest
     */
    'subtitles'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ApiV1MoviesIdPutRequest
     */
    'audioLanguages'?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof ApiV1MoviesIdPutRequest
     */
    'rating'?: number;
}

