/* tslint:disable */
/* eslint-disable */
/**
 * MovieSpot API
 * Especificações da API para o back-end da aplicação MovieSpot
 *
 * The version of the OpenAPI document: 1/
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ApiV1UsersPost201Response
 */
export interface ApiV1UsersPost201Response {
    /**
     * 
     * @type {string}
     * @memberof ApiV1UsersPost201Response
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1UsersPost201Response
     */
    'cpf': string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1UsersPost201Response
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1UsersPost201Response
     */
    'phone': string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1UsersPost201Response
     */
    'password': string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1UsersPost201Response
     */
    'role'?: ApiV1UsersPost201ResponseRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiV1UsersPost201Response
     */
    'id': string;
}

export const ApiV1UsersPost201ResponseRoleEnum = {
    Client: 'CLIENT',
    Admin: 'ADMIN',
    Owner: 'OWNER'
} as const;

export type ApiV1UsersPost201ResponseRoleEnum = typeof ApiV1UsersPost201ResponseRoleEnum[keyof typeof ApiV1UsersPost201ResponseRoleEnum];


