/* tslint:disable */
/* eslint-disable */
/**
 * MovieSpot API
 * Especificações da API para o back-end da aplicação MovieSpot
 *
 * The version of the OpenAPI document: 1/
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ApiV1UsersGet200ResponseInner
 */
export interface ApiV1UsersGet200ResponseInner {
    /**
     * 
     * @type {string}
     * @memberof ApiV1UsersGet200ResponseInner
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1UsersGet200ResponseInner
     */
    'cpf': string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1UsersGet200ResponseInner
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1UsersGet200ResponseInner
     */
    'phone': string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1UsersGet200ResponseInner
     */
    'password': string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1UsersGet200ResponseInner
     */
    'role'?: ApiV1UsersGet200ResponseInnerRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiV1UsersGet200ResponseInner
     */
    'id': string;
}

export const ApiV1UsersGet200ResponseInnerRoleEnum = {
    Client: 'CLIENT',
    Admin: 'ADMIN',
    Owner: 'OWNER'
} as const;

export type ApiV1UsersGet200ResponseInnerRoleEnum = typeof ApiV1UsersGet200ResponseInnerRoleEnum[keyof typeof ApiV1UsersGet200ResponseInnerRoleEnum];


