openapi: 3.0.1
info:
  title: MoviesSpot API
  version: 1.0.0
  description: This is a movie rental store api
  contact:
    name: API Support
    url: http://www.swagger.io/support
    email: gabrielhenriquedps@gmail.com

servers:
  - url: http://localhost:3000/api/v1
    description: Local server
  - url: https://api.moviespot.com/api/v1
    description: Production server

paths:
  /auth/login:
    $ref: './auth/login.yaml#/~1auth~1login'