/* tslint:disable */
/* eslint-disable */
/**
 * Cyclop APIs
 * Welcome to the Cyclop API service\'s documentation. You can play around with the different API endpoints to familiarise yourself with. --- **Release notes:**   * Improvments in CI/CD   * Platform endpoint   * Update password endpoint   * Profiles Endpoint   * JWT token revogation    * Test coverage improvment 10% - 20%   * Unit tests fix 
 *
 * The version of the OpenAPI document: {version}
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
/**
 * SchemeApi - axios parameter creator
 * @export
 */
export const SchemeApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Returns all schemes
         * @summary Get all schemes
         * @param {string} pageNum page number
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllSchemes: async (pageNum: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'pageNum' is not null or undefined
            assertParamExists('getAllSchemes', 'pageNum', pageNum)
            const localVarPath = `/document/schemes/{pageNum}`
                .replace(`{${"pageNum"}}`, encodeURIComponent(String(pageNum)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns all subschemes
         * @summary Get all subschemes
         * @param {string} pageNum page number
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllSubschemes: async (pageNum: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'pageNum' is not null or undefined
            assertParamExists('getAllSubschemes', 'pageNum', pageNum)
            const localVarPath = `/document/subschemes/{pageNum}`
                .replace(`{${"pageNum"}}`, encodeURIComponent(String(pageNum)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns all subschemes
         * @summary Get all subschemes
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllSubschemesWithoutPagination: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/document/subschemes`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns a scheme
         * @summary Get scheme by type
         * @param {string} type Type of scheme to return (Ex: bsd)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSchemeByType: async (type: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'type' is not null or undefined
            assertParamExists('getSchemeByType', 'type', type)
            const localVarPath = `/document/scheme/{type}`
                .replace(`{${"type"}}`, encodeURIComponent(String(type)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns a subscheme
         * @summary Get subscheme by type
         * @param {string} type Type of subscheme to return (Ex: BSDEmetteur, BSDChantier, and BSDExutoire...)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSubschemeByType: async (type: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'type' is not null or undefined
            assertParamExists('getSubschemeByType', 'type', type)
            const localVarPath = `/document/subscheme/{type}`
                .replace(`{${"type"}}`, encodeURIComponent(String(type)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SchemeApi - functional programming interface
 * @export
 */
export const SchemeApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SchemeApiAxiosParamCreator(configuration)
    return {
        /**
         * Returns all schemes
         * @summary Get all schemes
         * @param {string} pageNum page number
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllSchemes(pageNum: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllSchemes(pageNum, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SchemeApi.getAllSchemes']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns all subschemes
         * @summary Get all subschemes
         * @param {string} pageNum page number
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllSubschemes(pageNum: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllSubschemes(pageNum, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SchemeApi.getAllSubschemes']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns all subschemes
         * @summary Get all subschemes
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllSubschemesWithoutPagination(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllSubschemesWithoutPagination(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SchemeApi.getAllSubschemesWithoutPagination']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns a scheme
         * @summary Get scheme by type
         * @param {string} type Type of scheme to return (Ex: bsd)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSchemeByType(type: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSchemeByType(type, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SchemeApi.getSchemeByType']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns a subscheme
         * @summary Get subscheme by type
         * @param {string} type Type of subscheme to return (Ex: BSDEmetteur, BSDChantier, and BSDExutoire...)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSubschemeByType(type: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSubschemeByType(type, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SchemeApi.getSubschemeByType']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SchemeApi - factory interface
 * @export
 */
export const SchemeApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SchemeApiFp(configuration)
    return {
        /**
         * Returns all schemes
         * @summary Get all schemes
         * @param {SchemeApiGetAllSchemesRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllSchemes(requestParameters: SchemeApiGetAllSchemesRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.getAllSchemes(requestParameters.pageNum, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns all subschemes
         * @summary Get all subschemes
         * @param {SchemeApiGetAllSubschemesRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllSubschemes(requestParameters: SchemeApiGetAllSubschemesRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.getAllSubschemes(requestParameters.pageNum, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns all subschemes
         * @summary Get all subschemes
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllSubschemesWithoutPagination(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.getAllSubschemesWithoutPagination(options).then((request) => request(axios, basePath));
        },
        /**
         * Returns a scheme
         * @summary Get scheme by type
         * @param {SchemeApiGetSchemeByTypeRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSchemeByType(requestParameters: SchemeApiGetSchemeByTypeRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.getSchemeByType(requestParameters.type, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns a subscheme
         * @summary Get subscheme by type
         * @param {SchemeApiGetSubschemeByTypeRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSubschemeByType(requestParameters: SchemeApiGetSubschemeByTypeRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.getSubschemeByType(requestParameters.type, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getAllSchemes operation in SchemeApi.
 * @export
 * @interface SchemeApiGetAllSchemesRequest
 */
export interface SchemeApiGetAllSchemesRequest {
    /**
     * page number
     * @type {string}
     * @memberof SchemeApiGetAllSchemes
     */
    readonly pageNum: string
}

/**
 * Request parameters for getAllSubschemes operation in SchemeApi.
 * @export
 * @interface SchemeApiGetAllSubschemesRequest
 */
export interface SchemeApiGetAllSubschemesRequest {
    /**
     * page number
     * @type {string}
     * @memberof SchemeApiGetAllSubschemes
     */
    readonly pageNum: string
}

/**
 * Request parameters for getSchemeByType operation in SchemeApi.
 * @export
 * @interface SchemeApiGetSchemeByTypeRequest
 */
export interface SchemeApiGetSchemeByTypeRequest {
    /**
     * Type of scheme to return (Ex: bsd)
     * @type {string}
     * @memberof SchemeApiGetSchemeByType
     */
    readonly type: string
}

/**
 * Request parameters for getSubschemeByType operation in SchemeApi.
 * @export
 * @interface SchemeApiGetSubschemeByTypeRequest
 */
export interface SchemeApiGetSubschemeByTypeRequest {
    /**
     * Type of subscheme to return (Ex: BSDEmetteur, BSDChantier, and BSDExutoire...)
     * @type {string}
     * @memberof SchemeApiGetSubschemeByType
     */
    readonly type: string
}

/**
 * SchemeApi - object-oriented interface
 * @export
 * @class SchemeApi
 * @extends {BaseAPI}
 */
export class SchemeApi extends BaseAPI {
    /**
     * Returns all schemes
     * @summary Get all schemes
     * @param {SchemeApiGetAllSchemesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SchemeApi
     */
    public getAllSchemes(requestParameters: SchemeApiGetAllSchemesRequest, options?: RawAxiosRequestConfig) {
        return SchemeApiFp(this.configuration).getAllSchemes(requestParameters.pageNum, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns all subschemes
     * @summary Get all subschemes
     * @param {SchemeApiGetAllSubschemesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SchemeApi
     */
    public getAllSubschemes(requestParameters: SchemeApiGetAllSubschemesRequest, options?: RawAxiosRequestConfig) {
        return SchemeApiFp(this.configuration).getAllSubschemes(requestParameters.pageNum, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns all subschemes
     * @summary Get all subschemes
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SchemeApi
     */
    public getAllSubschemesWithoutPagination(options?: RawAxiosRequestConfig) {
        return SchemeApiFp(this.configuration).getAllSubschemesWithoutPagination(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns a scheme
     * @summary Get scheme by type
     * @param {SchemeApiGetSchemeByTypeRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SchemeApi
     */
    public getSchemeByType(requestParameters: SchemeApiGetSchemeByTypeRequest, options?: RawAxiosRequestConfig) {
        return SchemeApiFp(this.configuration).getSchemeByType(requestParameters.type, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns a subscheme
     * @summary Get subscheme by type
     * @param {SchemeApiGetSubschemeByTypeRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SchemeApi
     */
    public getSubschemeByType(requestParameters: SchemeApiGetSubschemeByTypeRequest, options?: RawAxiosRequestConfig) {
        return SchemeApiFp(this.configuration).getSubschemeByType(requestParameters.type, options).then((request) => request(this.axios, this.basePath));
    }
}

