/* tslint:disable */
/* eslint-disable */
/**
 * MovieSpot API
 * Especificações da API para o back-end da aplicação MovieSpot
 *
 * The version of the OpenAPI document: 1/
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ApiV1UsersIdPutRequest
 */
export interface ApiV1UsersIdPutRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiV1UsersIdPutRequest
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1UsersIdPutRequest
     */
    'cpf'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1UsersIdPutRequest
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1UsersIdPutRequest
     */
    'phone'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1UsersIdPutRequest
     */
    'password'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1UsersIdPutRequest
     */
    'role'?: ApiV1UsersIdPutRequestRoleEnum;
}

export const ApiV1UsersIdPutRequestRoleEnum = {
    Client: 'CLIENT',
    Admin: 'ADMIN',
    Owner: 'OWNER'
} as const;

export type ApiV1UsersIdPutRequestRoleEnum = typeof ApiV1UsersIdPutRequestRoleEnum[keyof typeof ApiV1UsersIdPutRequestRoleEnum];


