/* tslint:disable */
/* eslint-disable */
/**
 * MovieSpot API
 * Especificações da API para o back-end da aplicação MovieSpot
 *
 * The version of the OpenAPI document: 1/
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ApiV1UsersPostRequest
 */
export interface ApiV1UsersPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiV1UsersPostRequest
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1UsersPostRequest
     */
    'cpf': string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1UsersPostRequest
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1UsersPostRequest
     */
    'phone': string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1UsersPostRequest
     */
    'password': string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1UsersPostRequest
     */
    'role'?: ApiV1UsersPostRequestRoleEnum;
}

export const ApiV1UsersPostRequestRoleEnum = {
    Client: 'CLIENT',
    Admin: 'ADMIN',
    Owner: 'OWNER'
} as const;

export type ApiV1UsersPostRequestRoleEnum = typeof ApiV1UsersPostRequestRoleEnum[keyof typeof ApiV1UsersPostRequestRoleEnum];


