/* tslint:disable */
/* eslint-disable */
/**
 * Cyclop APIs
 * Welcome to the Cyclop API service\'s documentation. You can play around with the different API endpoints to familiarise yourself with. --- **Release notes:**   * Improvments in CI/CD   * Platform endpoint   * Update password endpoint   * Profiles Endpoint   * JWT token revogation    * Test coverage improvment 10% - 20%   * Unit tests fix 
 *
 * The version of the OpenAPI document: {version}
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Project } from './project';

/**
 * 
 * @export
 * @interface ProjectApiResponse
 */
export interface ProjectApiResponse {
    /**
     * The current page number.
     * @type {number}
     * @memberof ProjectApiResponse
     */
    'currentPage'?: number;
    /**
     * The number of items per page.
     * @type {number}
     * @memberof ProjectApiResponse
     */
    'perPage'?: number;
    /**
     * The total number of items across all pages.
     * @type {number}
     * @memberof ProjectApiResponse
     */
    'total'?: number;
    /**
     * The total number of pages.
     * @type {number}
     * @memberof ProjectApiResponse
     */
    'totalPages'?: number;
    /**
     * List of projects in the current page.
     * @type {Array<Project>}
     * @memberof ProjectApiResponse
     */
    'data'?: Array<Project>;
    /**
     * 
     * @type {string}
     * @memberof ProjectApiResponse
     */
    'status'?: ProjectApiResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof ProjectApiResponse
     */
    'message'?: string;
}

export const ProjectApiResponseStatusEnum = {
    Success: 'success',
    Fail: 'fail'
} as const;

export type ProjectApiResponseStatusEnum = typeof ProjectApiResponseStatusEnum[keyof typeof ProjectApiResponseStatusEnum];


