/* tslint:disable */
/* eslint-disable */
/**
 * Cyclop APIs
 * Welcome to the Cyclop API service\'s documentation. You can play around with the different API endpoints to familiarise yourself with. --- **Release notes:**   * Improvments in CI/CD   * Platform endpoint   * Update password endpoint   * Profiles Endpoint   * JWT token revogation    * Test coverage improvment 10% - 20%   * Unit tests fix 
 *
 * The version of the OpenAPI document: {version}
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {number}
     * @memberof User
     */
    'userId': number;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    'inactive'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'branch'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'photo'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'photoContentType'?: string;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    'createdBy'?: number;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'createdOn'?: string;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    'modifiedBy'?: number;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'modifiedOn'?: string;
}

